[package]
name = "multiformats"
version = "1.0.0"
description = "A Motoko library for working with Multiformats, including multicodec, multihash, and multibase."
repository = "https://github.com/edjcase/motoko_multiformats"
keywords = ["multiformats", "multicodec", "multihash", "multibase", "ipld"]
license = "MIT"

[dependencies]
base = "0.14.14"
new-base = "0.4.0"
base-x-encoder = "1.1.0"
leb128 = "0.0.2"

[dev-dependencies]
test = "2.1.1"

[toolchain]
moc = "0.14.14"
